// <auto-generated />
using System;
using DSaladin.Frnq.Api;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DSaladin.Frnq.Api.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DSaladin.Frnq.Api.Investment.InvestmentModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("PricePerUnit")
                        .HasColumnType("numeric");

                    b.Property<string>("ProviderId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("QuoteSymbol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TotalFees")
                        .HasColumnType("numeric");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProviderId", "QuoteSymbol");

                    b.ToTable("investment");
                });

            modelBuilder.Entity("DSaladin.Frnq.Api.Quote.QuoteModel", b =>
                {
                    b.Property<string>("ProviderId")
                        .HasColumnType("text");

                    b.Property<string>("Symbol")
                        .HasColumnType("text");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExchangeDisposition")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TypeDisposition")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ProviderId", "Symbol");

                    b.ToTable("quote");
                });

            modelBuilder.Entity("DSaladin.Frnq.Api.Quote.QuotePrice", b =>
                {
                    b.Property<string>("ProviderId")
                        .HasColumnType("text");

                    b.Property<string>("Symbol")
                        .HasColumnType("text");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("AdjustedClose")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Close")
                        .HasColumnType("numeric");

                    b.Property<decimal>("High")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Low")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Open")
                        .HasColumnType("numeric");

                    b.HasKey("ProviderId", "Symbol", "Date");

                    b.ToTable("quote_price");
                });

            modelBuilder.Entity("DSaladin.Frnq.Api.Investment.InvestmentModel", b =>
                {
                    b.HasOne("DSaladin.Frnq.Api.Quote.QuoteModel", "Quote")
                        .WithMany()
                        .HasForeignKey("ProviderId", "QuoteSymbol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quote");
                });

            modelBuilder.Entity("DSaladin.Frnq.Api.Quote.QuotePrice", b =>
                {
                    b.HasOne("DSaladin.Frnq.Api.Quote.QuoteModel", "Quote")
                        .WithMany("Prices")
                        .HasForeignKey("ProviderId", "Symbol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quote");
                });

            modelBuilder.Entity("DSaladin.Frnq.Api.Quote.QuoteModel", b =>
                {
                    b.Navigation("Prices");
                });
#pragma warning restore 612, 618
        }
    }
}
